### Returns all professional documents from MongoDB
GET http://localhost:8080/professional

### Returns a single professional document by MongoDB ObjectId
GET http://localhost:8080/professional/6963cf8332df10a5a2ff50d8
